services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
  server:
    build: .
    command: sh -c "/wait-for-it.sh db:3306 -- flask run --host=0.0.0.0 --port=80"
    volumes:
      - .:/app
    ports:
      - "8000:80"
    depends_on:
      - db
